### Register a new user
POST http://localhost:5001/api/admin/RegisterUser
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjVjNzE2YjJkLTg3NDEtNDJiNi04MDNjLTgzYWI4MWE5MzFmMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzY0OTAxMzI3fQ.xCVOtrnXxYyTjyLjsfnR_I36dAfO6V1rZDPycU_VVefiv6dS7gfUe-6Z_-TRz6nEYyIFPBZw0pHlRS6aehC20Q
Content-Type: application/json

{
    "email": "test123@test.com",
    "firstName": "Test123",
    "lastName": "User123",
    "phoneNumber": "+4573491124",
    "language": "en"
}

### Login a user
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Password123!"
}

### Login a user V2
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "Password123!"
}

### Update a user email
PUT http://localhost:5001/api/UserController/UpdateUserEmail
Content-Type: application/json

{
  "userId": "70a7ab31-b33b-4e12-b2aa-71748168bc3e",
  "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoidXNlciIsIkVtYWlsIjoidGVzdHVzZXJAbWVtb2hvdXNlLmNvbSIsIklkIjoiNzBhN2FiMzEtYjMzYi00ZTEyLWIyYWEtNzE3NDgxNjhiYzNlIiwiRXhwIjoiMTc0Njk1Nzk5NiJ9.AwZSaiLTXuc9Z2YH7xqQ_bAnHlEikzWixfNr1tW4v_u-YNlWkbLRhVOCFHZNBKS3-pZgc3D4_xi3TStBN0ElKw",
  "email": "changewasmade@momaemail.com"
}

### Delete a user email
DELETE http://localhost:5001/api/UserController/DeleteUser
Content-Type: application/json

"317c651d-1fd5-4ef9-8966-8a5996ac0144"