### Register a new user
###Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlODgxMzVlLTk3YjMtNDZiZC1hYWIwLTRlM2Q0ZjhkMTJkZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNzY0NzcwNTg4fQ.PDQDIaOZ-9tPUmeQYTvOXw2QrcHkNHbAj76oxwx5K4MdmAiIpUoVaB8pvHLpvxGg3uGNyf-hcTMAyaOd8yx3wQ
POST http://localhost:5001/api/admin/RegisterUser
Content-Type: application/json

{
    "email": "test123@test.com",
    "firstName": "Test123",
    "lastName": "User123",
    "phoneNumber": "+4573491124",
    "language": "en"
}

### Login a user
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Password123!"
}

### Login a user V2
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "ciTNNrX8E@zL"
}

### Update a user email
PUT http://localhost:5001/api/UserController/UpdateUserEmail
Content-Type: application/json

{
  "userId": "70a7ab31-b33b-4e12-b2aa-71748168bc3e",
  "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoidXNlciIsIkVtYWlsIjoidGVzdHVzZXJAbWVtb2hvdXNlLmNvbSIsIklkIjoiNzBhN2FiMzEtYjMzYi00ZTEyLWIyYWEtNzE3NDgxNjhiYzNlIiwiRXhwIjoiMTc0Njk1Nzk5NiJ9.AwZSaiLTXuc9Z2YH7xqQ_bAnHlEikzWixfNr1tW4v_u-YNlWkbLRhVOCFHZNBKS3-pZgc3D4_xi3TStBN0ElKw",
  "email": "changewasmade@momaemail.com"
}

### Delete a user email
DELETE http://localhost:5001/api/UserController/DeleteUser
Content-Type: application/json

"317c651d-1fd5-4ef9-8966-8a5996ac0144"