### Register a new user
POST http://localhost:5001/api/admin/usermanagement/RegisterUser
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YzcxNmIyZC04NzQxLTQyYjYtODAzYy04M2FiODFhOTMxZjAiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwibmJmIjoxNzYxNjg4NDM2LCJleHAiOjE3NjE3NzQ4MzZ9.UpUK7D6DYBKziAVsZdQtObcSmR95OiudRyODCgBv7J2u-U9RZbUDVG7FV2IomAe8IsaXRs0523xDMTUBnF_nJw
Content-Type: application/json

{
    "email": "another@test.com",
    "firstName": "Test123",
    "lastName": "User123",
    "phoneNumber": "+4573491124",
    "language": "en"
}

### Login a admin
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Password123!"
}

### Login a user 
POST http://localhost:5001/api/auth/Login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "Password123!"
}
